version: "3.8"
services:
  # PHP + Apache Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hrm_app
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost:8080
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=hrm_systems
      - DB_USERNAME=hrm_user
      - DB_PASSWORD=secret
    depends_on:
      - db
    networks:
      - hrm_network

  # MySQL Service
  db:
    image: mysql:8.0
    container_name: hrm_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: hrm_systems
      MYSQL_USER: hrm_user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - hrm_network

networks:
  hrm_network:
    driver: bridge

volumes:
  dbdata:
    driver: local
